# Generated by Django 4.2.5 on 2023-09-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='province',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='province',
            new_name='district',
        ),
    ]
