# Generated by Django 4.2.5 on 2023-09-19 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0002_rename_province_district_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('information', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='region.city')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.TextField(blank=True, default='')),
                ('time_departure', models.TimeField()),
                ('time_arrival', models.TimeField()),
                ('seat', models.BigIntegerField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bus', to='busRoute.bus')),
                ('departure_terminal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departure_terminal', to='busRoute.terminal')),
                ('destination_terminal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destination_terminal', to='busRoute.terminal')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
                'ordering': ('id',),
            },
        ),
    ]
