# Generated by Django 4.2.5 on 2023-09-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busRoute', '0002_alter_route_price_alter_route_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='seat',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
